import java.util.*
import java.lang.Exception
fun main() {
    val scanner = Scanner(System.`in`)

    val a=scanner.next().toCharArray()
    val b=scanner.next().toCharArray()
    val c=scanner.next().toCharArray()
    val d=scanner.next().toCharArray()

    print(a[0].isDigit())
    print("\\")
    print(b[0].isDigit())
    print("\\")
    print(c[0].isDigit())
    print("\\")
    print(d[0].isDigit())


}
